blank_issues_enabled: true
contact_links:
- name: 👉 Problem with djLint? Open an issue here.
  url: https://github.com/Riverside-Healthcare/djLint/issues
  about: |
    Having a problem with djLints's formatting, linting, or other features?
