name: Publish
on:
  push:
    tags:
      - v*
  workflow_dispatch:
jobs:
  publish-vsce:
    runs-on: ubuntu-24.04
    if: ${{ github.repository_owner == 'djlint' }}
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm
          check-latest: true
      - run: npm ci
      - run: npx --yes @vscode/vsce publish
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
  publish-ovsx:
    runs-on: ubuntu-24.04
    if: ${{ github.repository_owner == 'djlint' }}
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm
          check-latest: true
      - run: npm ci
      - run: npx --yes ovsx publish
        env:
          OVSX_PAT: ${{ secrets.OVSX_PAT }}
