name: Publish
on:
  push:
    tags:
      - v*
jobs:
  publish-vsce:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: npm
      - run: npm ci
      - run: npx vsce publish -p '${{ secrets.VSCE_PAT }}'
  publish-ovsx:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: npm
      - run: npm ci
      - run: npx ovsx publish -p '${{ secrets.OVSX_PAT }}'
