name: Update dependencies
on:
  workflow_dispatch:
  schedule:
    - cron: 0 6 * * *
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  update-npm-lock:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm update --lockfile-version 2
      - uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.PAT }}
          commit-message: Update package-lock.json
          committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          branch: update/npm-lock
          title: Update package-lock.json
          body:
  update-pre-commit-config:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: pipx install pre-commit
      - run: pre-commit autoupdate
      - uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.PAT }}
          commit-message: Update .pre-commit-config.yaml
          committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          branch: update/pre-commit-config
          title: Update .pre-commit-config.yaml
          body:
